version: '3.8'  # Specify Docker Compose version

services:
  postgres:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: postgres-db  # Name the container for easy reference
    environment:
      POSTGRES_USER: testuser  # Database username
      POSTGRES_PASSWORD: testpassword  # Database password
      POSTGRES_DB: testdb  # Default database name
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data in a named volume
    healthcheck:  # Ensure the database is ready
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped  # Restart policy

volumes:
  postgres-data:  # Define the named volume for data persistence